application:
  port: 8099

mongo:
  username: ""
  password: ""
  port: 27017
  host: "10.20.30.20"
  db: "study_pwa"
  collection: "users"
  require_auth: false

redis:
  url: "redis://10.20.30.5:6379"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60
